apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am UAT!
  labels:
    app: hello
    org: acmeUat
    variant: uat
  name: uat-the-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      deployment: hello
      org: acmeUat
      variant: uat
  template:
    metadata:
      annotations:
        note: Hello, I am UAT!
      labels:
        app: hello
        deployment: hello
        org: acmeUat
        variant: uat
    spec:
      containers:
      - image: nginx
        name: the-container
