apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am UAT!
  labels:
    app: hello
    org: acmeUat
    variant: uat
  name: uat-vcard-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
    org: acmeUat
    variant: uat
